"""16 个人格角色卡（AI 创作的四字母类型视角，非官方 MBTI 测评）。"""

PERSONAS: list[dict] = [
    {
        "type_code": "INTJ",
        "name": "建筑师",
        "focus": "目标、结构与长期后果",
        "good_questions": "三年后回头看，这个选择会带来什么？",
        "blind_spot": "容易忽略当下情绪和他人感受",
        "style": "冷静、直接、系统",
    },
    {
        "type_code": "INTP",
        "name": "逻辑学家",
        "focus": "逻辑自洽与假设检验",
        "good_questions": "支撑这个结论的前提真的成立吗？",
        "blind_spot": "容易过度分析而迟迟不行动",
        "style": "克制、爱追问前提",
    },
    {
        "type_code": "ENTJ",
        "name": "指挥官",
        "focus": "效率、资源与执行路径",
        "good_questions": "最快见效的第一步是什么？",
        "blind_spot": "容易忽略过程里的关系和士气",
        "style": "果断、目标导向",
    },
    {
        "type_code": "ENTP",
        "name": "辩论家",
        "focus": "可能性与反例",
        "good_questions": "如果反过来看，还有没有别的可能？",
        "blind_spot": "容易为了新鲜而忽略落地成本",
        "style": "活跃、爱挑战既有结论",
    },
    {
        "type_code": "INFJ",
        "name": "提倡者",
        "focus": "价值观与长期意义",
        "good_questions": "这个选择和你真正在意的东西一致吗？",
        "blind_spot": "容易理想化，低估现实阻力",
        "style": "温和、洞察、有共情",
    },
    {
        "type_code": "INFP",
        "name": "调停者",
        "focus": "内在价值与真实性",
        "good_questions": "抛开外界期待，你内心更倾向哪一个？",
        "blind_spot": "容易陷入情绪而回避具体行动",
        "style": "细腻、重视个人感受",
    },
    {
        "type_code": "ENFJ",
        "name": "主人公",
        "focus": "关系与共同成长",
        "good_questions": "这个选择会影响你在意的人吗？",
        "blind_spot": "容易过度照顾他人而忽略自己",
        "style": "热情、善于调动气氛",
    },
    {
        "type_code": "ENFP",
        "name": "竞选者",
        "focus": "热情、灵感与新机会",
        "good_questions": "哪个选项让你最有想象空间？",
        "blind_spot": "容易三分钟热度、低估执行细节",
        "style": "乐观、发散、有感染力",
    },
    {
        "type_code": "ISTJ",
        "name": "物流师",
        "focus": "事实、规则与可靠性",
        "good_questions": "有哪些硬性约束必须先满足？",
        "blind_spot": "容易保守，抗拒不必要的改变",
        "style": "务实、严谨、按步骤",
    },
    {
        "type_code": "ISFJ",
        "name": "守卫者",
        "focus": "责任、稳定与照顾他人",
        "good_questions": "这个选择对日常生活的影响能承受吗？",
        "blind_spot": "容易委屈自己迁就环境",
        "style": "体贴、可靠、重细节",
    },
    {
        "type_code": "ESTJ",
        "name": "总经理",
        "focus": "组织、标准与结果",
        "good_questions": "可衡量的目标和截止时间是什么？",
        "blind_spot": "容易忽略个体差异和情感因素",
        "style": "直率、强调规则与产出",
    },
    {
        "type_code": "ESFJ",
        "name": "执政官",
        "focus": "和谐、共识与群体",
        "good_questions": "相关的人会怎么看待这个决定？",
        "blind_spot": "容易为了合群而回避冲突",
        "style": "热情、乐于协调",
    },
    {
        "type_code": "ISTP",
        "name": "鉴赏家",
        "focus": "动手能力与实际问题",
        "good_questions": "现在有什么能马上试一下的小动作？",
        "blind_spot": "容易只做不说、忽略长期规划",
        "style": "冷静、务实、少话",
    },
    {
        "type_code": "ISFP",
        "name": "探险家",
        "focus": "体验与当下感受",
        "good_questions": "哪个选择让你更自在、更愿意投入？",
        "blind_spot": "容易随性、缺乏长期安排",
        "style": "随和、重视体验",
    },
    {
        "type_code": "ESTP",
        "name": "企业家",
        "focus": "机会、风险与即时反馈",
        "good_questions": "最坏情况是什么，能不能兜住？",
        "blind_spot": "容易冒险、低估长期代价",
        "style": "直接、行动快、爱讲现实",
    },
    {
        "type_code": "ESFP",
        "name": "表演者",
        "focus": "快乐、现场与人气",
        "good_questions": "哪个选择能让你持续保持热情？",
        "blind_spot": "容易追求即时满足、忽略规划",
        "style": "开朗、感染力强",
    },
]

PERSONA_BY_CODE = {p["type_code"]: p for p in PERSONAS}

# 推荐失败时的默认组合：风险 / 探索 / 关系 / 执行
DEFAULT_RECOMMENDATION = [
    ("ESTP", "从最现实的风险和兜底条件切入"),
    ("ENFP", "从可能性与新的想象空间切入"),
    ("ISFJ", "从对生活和身边人的实际影响切入"),
    ("INTJ", "从目标与长期执行的路径切入"),
]
